name: nighttune-backend

services:
  nighttune-backend:
    image: ghcr.io/houthacker/nighttune-backend:main
    container_name: nighttune-backend
    ports:
      - "127.0.0.1:3333:3333"
    volumes:
      - /home/user/nighttune-backend/.env.production:/app/.env.production
      - /home/user/nighttune-backend/.env.keys:/app/.env.keys
      - type: bind
        source: /home/user/nighttune-backend/data
        target: /data
